controller:
  updateStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 1
  hostPort:
    enabled: true
  terminationGracePeriodSeconds: 0
  service:
    type: "NodePort"
  watchIngressWithoutClass: true
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"
  publishService:
    enabled: false
  extraArgs:
    publish-status-address: "localhost"
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
    # prometheus.io/scheme: http
    # prometheus.io/path: /metrics
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: "kube-prometheus-stack"
      enabled: true