# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

global:
  # How frequently to scrape targets
  scrape_interval:     10s
  # How frequently to evaluate rules
  evaluation_interval: 10s

alertmanager:
  alertmanagerSpec:
    externalURL: http://alert.localtest.me
  config:
    receivers:
      - name: 'null'
      - name: Watchdog-HealthCheck.io
        webhook_configs:
          - url: https://hc-ping.com/bdc7a25a-f522-4ccc-b801-2ee226e0c03d
      # - name: DEAD-MAN-SNITCH
      #   webhook_configs:
      #     - url: "https://nosnch.in/112081fd96"
      - name: dev-kind-slack
        slack_configs:
        - api_url: https://hooks.slack.com/services/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
          channel: '#dev-kind'
          title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
          title_link: 'http://alert.localtest.me/#/alerts'
          text: >-
            {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
              *Description:* {{ .Annotations.description }}
              *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}

    route:
      routes:
        - match:
            alertname: Watchdog
          receiver: Watchdog-HealthCheck.io
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
          continue: true
        # - match:
        #     alertname: Watchdog-Watchdog
        #   receiver: DEAD-MAN-SNITCH
        #   group_wait: 0s
        #   group_interval: 1m
        #   repeat_interval: 50s
        - match:
            alertname: TargetDown
            namespace: kube-system
          receiver: dev-kind-slack
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: TargetDown
            namespace: nginx
          receiver: dev-kind-slack
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: TargetDown
            namespace: monitoring
          receiver: dev-kind-slack
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: TargetDown
            namespace: logging
          receiver: dev-kind-slack
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: etcdInsufficientMembers
          receiver: dev-kind-slack
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: AlertmanagerClusterFailedToSendAlerts
          receiver: dev-kind-slack
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: AlertmanagerFailedToSendAlerts
          receiver: dev-kind-slack
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: FluentdCloudWatchLogsNotShipping
            namespace: logging
          receiver: dev-kind-slack
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s

prometheus:
  prometheusSpec:
    web:
      externalUrl: http://prom.localtest.me
    externalUrl: http://prom.localtest.me


prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
