global:
  # How frequently to scrape targets
  scrape_interval:     10s
  # How frequently to evaluate rules
  evaluation_interval: 10s

alertmanager:
  config:
    receivers:
      - name: 'null'
      - name: Watchdog-HealthCheck.io
        webhook_configs:
          - url: "https://hc-ping.com/bdc7a25a-f522-4ccc-b801-2ee226e0c03d"
      - name: Kubernetes-HealthCheck.io
        webhook_configs:
          - url: "https://hc-ping.com/436b4c11-9c16-4008-9d23-2e6a17f861ff"
      - name: Monitoring-HealthCheck.io
        webhook_configs:
          - url: "https://hc-ping.com/40fd1b7d-f238-4384-b534-a5ba7892daab"
      - name: Nginx-HealthCheck.io
        webhook_configs:
          - url: "https://hc-ping.com/2e723541-2b97-4782-a049-f407287ef257"
      - name: Logging-HealthCheck.io
        webhook_configs:
          - url: "https://hc-ping.com/aa9f326c-d958-4b45-82c4-1b107c03762b"
      - name: DEAD-MAN-SNITCH
        webhook_configs:
          - url: "https://nosnch.in/112081fd96"
    route:
      routes:
        - match:
            alertname: Watchdog
          receiver: Watchdog-HealthCheck.io
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
          continue: true
        - match:
            alertname: Watchdog-Watchdog
          receiver: DEAD-MAN-SNITCH
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: TargetDown
            namespace: kube-system
          receiver: Kubernetes-HealthCheck.io
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: TargetDown
            namespace: nginx
          receiver: Nginx-HealthCheck.io
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: TargetDown
            namespace: monitoring
          receiver: Monitoring-HealthCheck.io
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s
        - match:
            alertname: TargetDown
            namespace: logging
          receiver: Logging-HealthCheck.io
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 50s

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
