---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluentd
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  # http://fluentd.localtest.me/
  - host: fluentd.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fluentd
            port:
              number: 24231