# kind -- DaemonSet or Deployment
kind: DaemonSet

image:
  repository: fluent/fluent-bit
  tag: 2.0.11-debug

testFramework:
  enabled: true
  image:
    repository: busybox
    pullPolicy: Always
    tag: latest

rbac:
  create: true
  nodeAccess: false

service:
  type: ClusterIP
  port: 2020
  annotations:
    prometheus.io/path: "/api/v1/metrics/prometheus"
    prometheus.io/port: "2020"
    prometheus.io/scrape: "true"

serviceMonitor:
  enabled: false
  namespace: monitoring
  interval: 10s
  scrapeTimeout: 10s
  jobLabel: fluentbit
  selector:
    prometheus: kube-prometheus-stack
    release: kube-prometheus-stack

prometheusRule:
  enabled: false
  namespace: logging
  additionalLabels:
  rules:
  - alert: NoOutputBytesProcessed
    expr: rate(fluentbit_output_proc_bytes_total[5m]) == 0
    annotations:
      message: |
        Fluent Bit instance {{ $labels.instance }}'s output plugin {{ $labels.name }} has not processed any
        bytes for at least 15 minutes.
      summary: No Output Bytes Processed
    for: 15m
    labels:
      severity: critical
  - alert: FluentdDown
    expr: up{job="fluentd"} == 0
    for: 5m
    labels:
      context: fluentd
      severity: warning
    annotations:
      summary: "Fluentd Down"
      description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
  - alert: FluentdScrapeMissing
    expr: absent(up{job="fluentd"} == 1)
    for: 3m
    labels:
      context: fluentd
      severity: warning
    annotations:
      summary: "Fluentd Scrape Missing"
      description: "Fluentd instance has disappeared from Prometheus target discovery"
  - alert: FluentdCloudWatchLogsNotShipping
    expr: fluentd_output_status_emit_records{plugin_id="ignore_fluent_logs",type="null"} > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Fluentd is not shipping logs to CloudWatch
      description: "Fluentd is not sending logs to CloudWatch. Check Fluentd's configuration and logs for errors."

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /api/v1/health
    port: http

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

## only available if kind is Deployment
ingress:
  enabled: false
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
  - host: fluent-bit.${cluster_name}.localtest.me
    port: 2020

metricsPort: 2020

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:
  customParsers: |
    [PARSER]
        Name docker
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path   /var/log/containers/fluent*
        multiline.parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [FILTER]
        Name record_modifier
        Match *
        Record clustername clusterName
        Record region region
        Record team team
        Record stage level
        Remove_key $.kubernetes.pod_id
        Remove_key $.kubernetes.master_url
        Remove_key $.kubernetes.container_image_id
        Remove_key $.kubernetes.namespace_id
    [FILTER]
        Name parser
        Match *
        Key_Name log
        Reserve_Data true
        Parser json

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name stdout
        Match *
    [OUTPUT]
        Name file
        Match *
        Path /var/log/containers

