---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluent-bit
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  # http://fluent-bit.localtest.me/
  - host: fluent-bit.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fluent-fluent-bit
            port:
              number: 2020