apiVersion: v1
kind: PersistentVolume
metadata:
  name: echo-pv-volume-read
  labels:
    type: local
spec:
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/data/read