apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-pv-claim-read
  namespace: echo
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi