global:
  datacenter: vault-kubernetes-guide

client:
  enabled: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0
ui:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - host: consul.localtest.me
      pathType: ImplementationSpecific
      paths:
        - /